In [ ]:
import numpy as np
np.array((2,2))

array([2, 2])

In [ ]:

c = np.full((3,3), fill_value=7)
print("\n3. Full array of 7s:")
print(c)


3. Full array of 7s:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
given = np.array([[1,2,3],[4,5,6]])
d = np.zeros_like(given)
print("\n. zeros_like(given):")
print(d)


. zeros_like(given):
[[0 0 0]
 [0 0 0]]


In [ ]:
e = np.ones_like(given)
print("\n5. ones_like(given):")
print(e)


5. ones_like(given):
[[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1,2,3,4]
f = np.array(new_list)
print("\n6. List → numpy array:")
print(f)


6. List → numpy array:
[1 2 3 4]


In [ ]:
#TASK2
print(" PROBLEM 2 ")

# 1
p1 = np.arange(10, 50)
print("\n1. Array 10–49:")
print(p1)

 PROBLEM 2 

1. Array 10–49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
p2 = np.arange(9).reshape(3,3)
print("\n2. 3x3 matrix (0–8):")
print(p2)


2. 3x3 matrix (0–8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
p3 = np.eye(3)
print("\n3. Identity matrix:")
print(p3)


3. Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a= np.random.random(30)
print("\n4. Random array (30 values):")
print(a)
print("Mean =", a.mean())


4. Random array (30 values):
[0.99378408 0.81762601 0.2940995  0.03291935 0.12777187 0.17135978
 0.57605865 0.68762666 0.15120237 0.35451608 0.38005675 0.56015616
 0.74348654 0.48101603 0.36273979 0.0798295  0.54417408 0.26455689
 0.46014446 0.96949137 0.29409954 0.65258912 0.63020201 0.32540197
 0.89355902 0.64502298 0.00374027 0.74760609 0.30452717 0.59705779]
Mean = 0.4715473964199694


In [ ]:
b4 = np.random.random(30)
print("\n4. Random array (30 values):")
print(b4)
print("Mean =", b4.mean())


4. Random array (30 values):
[0.12801683 0.69597363 0.08303732 0.14835759 0.80299532 0.08033327
 0.16030098 0.62840963 0.75994089 0.8283895  0.62807479 0.61325625
 0.72647101 0.55907562 0.88699626 0.26530311 0.90710816 0.45247492
 0.31647987 0.30579222 0.46888052 0.86358311 0.66485927 0.01845682
 0.69086338 0.78134499 0.85872529 0.63397886 0.64988536 0.56930033]
Mean = 0.5392221700872978


In [ ]:
aa = np.zeros(10)
a[4] = 1
print("\n6. Zero array with 5th element = 1:")
print(aa)


6. Zero array with 5th element = 1:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1,2,0,0,4,0])
p7 = arr[::-1]
print("\n7. Reversed array:")
print(p7)


7. Reversed array:
[0 4 0 0 2 1]


In [ ]:
p8 = np.ones((6,6))
p8[1:-1, 1:-1] = 0
print("\n8. 2D array with border 1 and inside 0:")
print(p8)


8. 2D array with border 1 and inside 0:
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:


p9 = np.zeros((8,8))
p9[1::2, ::2] = 1
p9[::2, 1::2] = 1
print("\n9. Checkerboard pattern:")
print(p9)


9. Checkerboard pattern:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#TASK3
print(" PROBLEM 3")

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

 PROBLEM 3


In [ ]:
# 1
print("\n1. x + y:")
print(x + y)



1. x + y:
[[ 6  8]
 [10 13]]


In [ ]:
# 2
print("\n2. x - y:")
print(x - y)


2. x - y:
[[-4 -4]
 [-4 -3]]


In [ ]:
# 3
print("\n3. x * 3:")
print(x * 3)


3. x * 3:
[[ 3  6]
 [ 9 15]]


In [ ]:

print("\n4. Square of x:")
print(x**2)



4. Square of x:
[[ 1  4]
 [ 9 25]]


In [ ]:
# 5
print("\n5. Dot products:")
print("v·w =", np.dot(v,w))
print("x·v =", np.dot(x,v))
print("x·y =\n", np.dot(x,y))


5. Dot products:
v·w = 219
x·v = [29 77]
x·y =
 [[19 22]
 [50 58]]


In [ ]:
# 6
print("\n6. Concatenate x & y (row-wise):")
print(np.concatenate((x,y), axis=0))
print("\nConcatenate v & w (column-wise):")
print(np.vstack((v,w)))


6. Concatenate x & y (row-wise):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w (column-wise):
[[ 9 10]
 [11 12]]


In [ ]:
print("\n7. Why x & v fails:")
print("Error: x is 2D but v is 1D → shapes don’t match.")


7. Why x & v fails:
Error: x is 2D but v is 1D → shapes don’t match.


In [ ]:
import numpy as np


In [ ]:

#TASK4
print("\n=== PROBLEM 4 ===")

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])



=== PROBLEM 4 ===


In [ ]:
# 1
A_inv = np.linalg.inv(A)
print("\n1. A × A⁻¹ = Identity:")
print(A.dot(A_inv))


1. A × A⁻¹ = Identity:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
# 2
AB = A.dot(B)
BA = B.dot(A)
print("\n2. AB:")
print(AB)
print("\nBA:")
print(BA)
print("\nAB != BA confirmed")


2. AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

AB != BA confirmed


In [ ]:
# 3
print("\n3. (AB)^T == B^T × A^T:")
print("LHS:\n", AB.T)
print("RHS:\n", B.T.dot(A.T))

# Solving system of equations
A_sys = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])
B_sys = np.array([-1, -3, 9])

solution = np.linalg.inv(A_sys).dot(B_sys)
print("\nSolution to system [x, y, z]:")
print(solution)


3. (AB)^T == B^T × A^T:
LHS:
 [[23 51]
 [13 29]]
RHS:
 [[23 51]
 [13 29]]

Solution to system [x, y, z]:
[ 2.  1. -2.]


In [ ]:
time_data = [1, 2, 3, 4, 5, 6, 7, 2.5, 4.5, 5.5]


low = []
moderate = []
high = []

In [ ]:
  np.array([[0,0],[0,0]])


array([[0, 0],
       [0, 0]])

In [ ]:
s=np.ones((4,2))
print(s)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
